"""add table Manufacture

Revision ID: 646be359543f
Revises: 7e27b47c566f
Create Date: 2025-05-23 08:15:38.067123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646be359543f'
down_revision = '7e27b47c566f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacture_base_info',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('pyName', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacture_base_info')
    # ### end Alembic commands ###
