"""修改了主键

Revision ID: 7e27b47c566f
Revises: a3ab04b33542
Create Date: 2025-05-18 00:32:18.646833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e27b47c566f'
down_revision = 'a3ab04b33542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wis_upload_product_dtl', schema=None) as batch_op:
        batch_op.alter_column('foreignId',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wis_upload_product_dtl', schema=None) as batch_op:
        batch_op.alter_column('foreignId',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
