"""add table : StoreInfo

Revision ID: 9d0e9b6a0caf
Revises: 646be359543f
Create Date: 2025-05-24 16:09:14.361896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0e9b6a0caf'
down_revision = '646be359543f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_info',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_info')
    # ### end Alembic commands ###
