"""创建各个表

Revision ID: a3ab04b33542
Revises: 
Create Date: 2025-05-17 23:25:24.579620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ab04b33542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mms_price_rpt',
    sa.Column('loginName', sa.String(length=50), nullable=False),
    sa.Column('commodityId', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('rptdate', sa.Date(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('linkman', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('leader', sa.String(length=50), nullable=False),
    sa.Column('statistician', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('commodityId')
    )
    op.create_table('ods_zdlsqy_sbxse_xb',
    sa.Column('TYSHXYDM', sa.String(length=40), nullable=False),
    sa.Column('DWMC', sa.String(length=40), nullable=False),
    sa.Column('BBQ', sa.String(length=12), nullable=False),
    sa.Column('DWFZR', sa.String(length=50), nullable=False),
    sa.Column('TBR', sa.String(length=50), nullable=False),
    sa.Column('LXDH', sa.String(length=20), nullable=False),
    sa.Column('BCRQ', sa.Date(), nullable=False),
    sa.Column('ZB', sa.String(length=8), nullable=False),
    sa.Column('BQZ', sa.Float(), nullable=True),
    sa.Column('QNTQZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('TYSHXYDM', 'BBQ', 'ZB')
    )
    op.create_table('price_type_dict',
    sa.Column('price_type_id', sa.String(length=20), nullable=False),
    sa.Column('price_type_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('price_type_id')
    )
    op.create_table('qy_code_dict',
    sa.Column('qy_code', sa.String(length=20), nullable=False),
    sa.Column('qy_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('qy_code', 'qy_name')
    )
    op.create_table('scjc_pl_dict',
    sa.Column('commodity_id', sa.String(length=20), nullable=False),
    sa.Column('commodity_name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=20), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('price_unit', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('commodity_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wis_day_jxc_rpt',
    sa.Column('loginName', sa.String(length=50), nullable=False),
    sa.Column('commodityId', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('instock', sa.Float(), nullable=False),
    sa.Column('rptdate', sa.Date(), nullable=False),
    sa.Column('createTime', sa.DateTime(), nullable=False),
    sa.Column('updateTime', sa.DateTime(), nullable=False),
    sa.Column('linkman', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('leader', sa.String(length=50), nullable=False),
    sa.Column('statistician', sa.String(length=50), nullable=False),
    sa.Column('originPlace', sa.String(length=6), nullable=False),
    sa.Column('manufacturerName', sa.String(length=150), nullable=False),
    sa.Column('manufacturerAddress', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('commodityId')
    )
    op.create_table('wis_upload_product_dtl',
    sa.Column('nodeCode', sa.String(length=20), nullable=True),
    sa.Column('foreignId', sa.String(length=20), nullable=True),
    sa.Column('commodityId', sa.String(length=20), nullable=False),
    sa.Column('stock', sa.Float(), nullable=False),
    sa.Column('instock', sa.Float(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('rptdate', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('commodityId')
    )
    op.create_table('xb_zb_dict',
    sa.Column('zb_id', sa.String(length=20), nullable=False),
    sa.Column('zb_name', sa.String(length=100), nullable=False),
    sa.Column('zb_unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('zb_id')
    )
    op.create_table('yjbg_ls_pl_dict',
    sa.Column('commodity_id', sa.String(length=20), nullable=False),
    sa.Column('commodity_name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('commodity_id')
    )
    op.create_table('yjbg_pf_pl_dict',
    sa.Column('commodity_id', sa.String(length=20), nullable=False),
    sa.Column('commodity_name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=20), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('commodity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yjbg_pf_pl_dict')
    op.drop_table('yjbg_ls_pl_dict')
    op.drop_table('xb_zb_dict')
    op.drop_table('wis_upload_product_dtl')
    op.drop_table('wis_day_jxc_rpt')
    op.drop_table('user')
    op.drop_table('scjc_pl_dict')
    op.drop_table('qy_code_dict')
    op.drop_table('price_type_dict')
    op.drop_table('ods_zdlsqy_sbxse_xb')
    op.drop_table('mms_price_rpt')
    # ### end Alembic commands ###
